spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://fullstackspringbootreactdb.co8xx54bpfj3.eu-central-1.rds.amazonaws.com:5432/studentlist
    username: postgres
    password: postgres
    pool-size: 30

